name: Unit Tests

on: 
  pull_request

jobs: 
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests==2.31.0 simplejson==3.19.2 pytest==7.4.3 pytest-mock==3.14.0 pyfiglet==1.0.2

      - name: Run tests
        run: |
          pytest
