name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.
      - name: run install and test
        run: |
          pip install pytest
          pytest unit_tests/test_fetch_data_postman.py